In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('C:/Users/rpcha/Desktop/Heart.csv')

In [3]:
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [4]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
data['ChestPain'] = encoder.fit_transform(data['ChestPain'])

In [5]:
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,1,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [7]:
data['Thal'] = encoder.fit_transform(data['Thal'])

In [8]:
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,No
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,Yes
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,Yes
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,No
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,Yes
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,Yes
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,Yes
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,Yes
302,303,38,1,1,138,175,0,0,173,0,0.0,1,NaN,1,No

In [9]:
data['AHD'] = encoder.fit_transform(data['AHD'])

In [10]:
data

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,0
1,2,67,1,0,160,286,0,2,108,1,1.5,2,3.0,1,1
2,3,67,1,0,120,229,0,2,129,1,2.6,2,2.0,2,1
3,4,37,1,1,130,250,0,0,187,0,3.5,3,0.0,1,0
4,5,41,0,2,130,204,0,2,172,0,1.4,1,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,3,110,264,0,0,132,0,1.2,2,0.0,2,1
299,300,68,1,0,144,193,1,0,141,0,3.4,2,2.0,2,1
300,301,57,1,0,130,131,0,0,115,1,1.2,2,1.0,2,1
301,302,57,0,2,130,236,0,2,174,0,0.0,2,1.0,1,1
302,303,38,1,1,138,175,0,0,173,0,0.0,1,NaN,1,0

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [21]:
data.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          0
AHD           0
dtype: int64

In [24]:
data['Ca'].fillna(data['Ca'].mean(),inplace=True)

In [25]:
data.isnull().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            0
Thal          0
AHD           0
dtype: int64

In [26]:
X = data.drop(columns=['AHD'])

In [27]:
y = data['AHD']

In [28]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
dt_classifier = DecisionTreeClassifier()
svm_classifier = SVC()
knn_classifier = KNeighborsClassifier()

In [30]:
dt_classifier.fit(X_train, y_train)
svm_classifier.fit(X_train, y_train)
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [31]:
dt_predictions = dt_classifier.predict(X_test)
svm_predictions = svm_classifier.predict(X_test)
knn_predictions = knn_classifier.predict(X_test)

In [32]:
dt_accuracy = accuracy_score(y_test, dt_predictions)
svm_accuracy = accuracy_score(y_test, svm_predictions)
knn_accuracy = accuracy_score(y_test, knn_predictions)

In [33]:
print("Decision Tree Accuracy:", dt_accuracy)
print("SVM Accuracy:", svm_accuracy)
print("KNN Accuracy:", knn_accuracy)

Decision Tree Accuracy: 0.8032786885245902
SVM Accuracy: 0.639344262295082
KNN Accuracy: 0.5245901639344263